name: db

on:
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
    - src/Services/IdentityServer/src/**
    - .github/workflows/db.yml

env:
  DOTNET_VERSION: 7.0.x
  REGISTRY_NAME: cradventureworks
  APP_NAME: adventureworks_mvc_store

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildLinux:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Github Action'
        uses: actions/checkout@master
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
        
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore ./src/Services/IdentityServer/src/AW.Services.IdentityServer.Database.Build/AW.Services.IdentityServer.Database.Build.csproj

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: csharp

      - name: Build and run unit tests
        run: |
          dotnet build ./src/Services/IdentityServer/src/AW.Services.IdentityServer.Database.Build/AW.Services.IdentityServer.Database.Build.csproj
    
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:csharp"
